name: carambar
description: A life simulation game

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^0.13.1
  equatable: ^2.0.0

dev_dependencies:
  integration_test: ^1.0.2+2
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  mockito: ^4.1.4

flutter:
  uses-material-design: true
